In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\user\desktop\project_lsb\venv\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\desktop\project_lsb\venv\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\desktop\project_lsb\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\user\desktop\project_lsb\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\user\desktop\project_lsb\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: c:\Users\user\Desktop\project_LSB\venv\Scripts\python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("data\DieCasting_Quality_Raw_Data.csv", header=1)

# 상위 5행 확인
df.head()

<>:4: SyntaxWarning: invalid escape sequence '\D'
<>:4: SyntaxWarning: invalid escape sequence '\D'
C:\Users\user\AppData\Local\Temp\ipykernel_6652\3469601164.py:4: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv("data\DieCasting_Quality_Raw_Data.csv", header=1)

,id,Product_Type,Shot,Velocity_1,Velocity_2,Velocity_3,High_Velocity,Cylinder_Pressure,Rapid_Rise_Time,Biscuit_Thickness,...,Blow_Hole_2,Stain_2,Dent_2,Deformation_2,Contamination_2,Impurity_2,Crack_2,Scratch_2,Buring_Mark_2,Inclusions_2
0,1,1,1,0.144,0.170,0.188,2.134,214,0.008,10,...,0,0,0,0,0,0,0,0,0,0
1,1002,1,2,0.144,0.170,0.182,2.124,217,0.008,11,...,0,0,0,0,0,0,0,0,0,0
2,2003,1,3,0.144,0.170,0.182,2.116,214,0.008,11,...,0,0,0,0,0,0,0,0,0,0
3,3004,1,4,0.144,0.170,0.182,2.137,217,0.008,11,...,0,0,0,0,0,0,0,0,0,0
4,4005,1,5,0.144,0.172,0.176,2.111,217,0.008,12,...,0,0,0,0,0,0,0,0,0,0

목적 : 생산 효율을 높이고 불량률을 낮추기 위해 공정 변수(주조 온도, 압력, 속도 등) 및 센서 데이터를 분석하여 불량 유형을 자동 예측하는 머신러닝 모델을 개발

{
    "공정_변수": {
        "속도": {
            "단계별_사출": ["Velocity_1", "Velocity_2", "Velocity_3"],
            "최고_사출": "High_Velocity"
        },
        "압력": {
            "실린더": "Cylinder_Pressure",
            "주조": "Casting_Pressure",
            "공기": ["Air_Pressure_Min", "Air_Pressure_Max"],
            "냉각수": "Coolant_Pressure"
        },
        "시간": ["Rapid_Rise_Time", "Cycle_Time", "Pressure_Rise_Time", "Spray_Time"],
        "물리량": ["Clamping_Force", "Factory_Humidity", "Factory_Temp", "Coolant_Temp"]
    },
    "불량_유형": {
        "표면": ["Stain", "Dent", "Scratch", "Buring_Mark"],
        "구조": ["Short_Shot", "Bubble", "Blow_Hole", "Deformation", "Crack"],
        "이물질": ["Contamination", "Impurity", "Inclusions"]
    }
}

1️⃣ 기본 정보

Shot: Shot 번호

id: 설비 ID

Product_Type: 제품 유형 (Type1, Type2)



2️⃣ 사출 및 압력 관련 변수

Velocity_1: 금형에 용탕을 투입하는 속도 (1단계)

Velocity_2: 금형에 용탕을 투입하는 속도 (2단계)

Velocity_3: 금형에 용탕을 투입하는 속도 (3단계)

High_Velocity: 고속 사출 속도

Cylinder_Pressure: Shot을 찍기 위한 실린더 압력

Casting_Pressure: Shot을 찍을 때의 압력

Clamping_Force: Shot을 찍을 때 금형을 밀어주는 힘

Rapid_Rise_Time: 실린더 압력 상승 시간

Pressure_Rise_Time: 주조 압력 상승 시간

Air_Pressure: 에어 압력 측정값

Air_Pressure_Min: 에어 압력 최소값

Air_Pressure_Max: 에어 압력 최대값



3️⃣ 시간 관련 변수

Cycle_Time: 제품이 나오기까지 걸리는 총 시간

Spray_Time: 스프레이 작업 시간

Spray_1_Time: 1차 스프레이 작업 시간

Spray_2_Time: 2차 스프레이 작업 시간



4️⃣ 온도 관련 변수

Melting_Furnace_Temp: 알루미늄을 녹여 일정 온도를 유지하는 장치 온도

Coolant_Temp: 냉각수 온도 측정값

Coolant_Temp_Min: 냉각수 온도 최소값

Coolant_Temp_Max: 냉각수 온도 최대값

Factory_Temp: 공장 온도 측정값

Factory_Temp_Min: 공장 온도 최소값

Factory_Temp_Max: 공장 온도 최대값



5️⃣ 습도 관련 변수

Factory_Humidity: 공장 습도 측정값

Factory_Humidity_Min: 공장 습도 최소값

Factory_Humidity_Max: 공장 습도 최대값



6️⃣ 기타 공정 변수

Biscuit_Thickness: 주조 비스켓 두께

Coolant_Pressure: 냉각수 압력 측정값



7️⃣ 불량 유형 (Cavity 1, 2 기준)

각 불량은 Cavity 1, 2에 대해 개별적으로 기록됨.

Short_Shot_1, 2: 미성형 불량

Bubble_1, 2: 기포 불량

Exfoliation_1, 2: 박리 불량

Blow_Hole_1, 2: 기공 불량

Stain_1, 2: 얼룩 불량

Dent_1, 2: 찍힘 불량

Deformation_1, 2: 평탄(변형) 불량

Contamination_1, 2: 오염 불량

Impurity_1, 2: 이물 불량

Crack_1, 2: 뜯김/균열 불량

Scratch_1, 2: 스크래치 불량

Buring_Mark_1, 2: 소착 불량

Inclusions_1, 2: 개재물 불량

In [50]:
df

,id,Product_Type,Shot,Velocity_1,Velocity_2,Velocity_3,High_Velocity,Cylinder_Pressure,Rapid_Rise_Time,Biscuit_Thickness,...,Blow_Hole_2,Stain_2,Dent_2,Deformation_2,Contamination_2,Impurity_2,Crack_2,Scratch_2,Buring_Mark_2,Inclusions_2
0,1,1,1,0.144,0.170,0.188,2.134,214,0.008,10,...,0,0,0,0,0,0,0,0,0,0
1,1002,1,2,0.144,0.170,0.182,2.124,217,0.008,11,...,0,0,0,0,0,0,0,0,0,0
2,2003,1,3,0.144,0.170,0.182,2.116,214,0.008,11,...,0,0,0,0,0,0,0,0,0,0
3,3004,1,4,0.144,0.170,0.182,2.137,217,0.008,11,...,0,0,0,0,0,0,0,0,0,0
4,4005,1,5,0.144,0.172,0.176,2.111,217,0.008,12,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7530,7530659,2,659,0.150,0.166,0.210,2.492,265,0.011,17,...,0,0,0,0,0,0,0,0,0,0
7531,7531660,2,660,0.144,0.174,0.206,2.514,264,0.011,16,...,0,0,0,0,0,0,0,0,0,0
7532,7532660,2,660,0.144,0.174,0.206,2.514,264,0.011,16,...,0,0,0,0,0,0,0,0,0,0
7533,7533661,2,661,0.147,0.174,0.204,2.532,265,0.012,18,...,0,0,0,0,0,0,0,0,0,0
7534,7534661,2,661,0.147,0.174,0.204,2.532,265,0.012,18,...,0,0,0,0,0,0,0,0,0,0

In [26]:
df.columns

Index(['id', 'Product_Type', 'Shot', 'Velocity_1', 'Velocity_2', 'Velocity_3',
       'High_Velocity', 'Cylinder_Pressure', 'Rapid_Rise_Time',
       'Biscuit_Thickness ', 'Clamping_Force ', 'Cycle_Time',
       ' Pressure_Rise_Time', 'Casting_Pressure', 'Spray_Time', 'Spray_1_Time',
       'Spray_2_Time', 'Melting_Furnace_Temp', 'Air_Pressure',
       'Air_Pressure_Min', 'Air_Pressure_Max', 'Coolant_Temp',
       'Coolant_Temp_Min', 'Coolant_Temp_Max', 'Coolant_Pressure',
       'Factory_Temp', 'Factory_Temp_Min', 'Factory_Temp_Max',
       'Factory_Humidity', 'Factory_Humidity_Min', 'Factory_Humidity_Max',
       'Short_Shot_1', 'Bubble_1', 'Exfoliation_1', 'Blow_Hole_1', 'Stain_1',
       'Dent_1', 'Deformation_1', 'Contamination_1', 'Impurity_1', 'Crack_1',
       'Scratch_1', 'Buring_Mark_1', 'Inclusions_1', 'Short_Shot_2',
       'Bubble_2', 'Exfoliation_2', 'Blow_Hole_2', 'Stain_2', 'Dent_2',
       'Deformation_2', 'Contamination_2', 'Impurity_2', 'Crack_2',
       'Scratch_2', 'Buring_Mark_2', 'Inclusions_2'],
      dtype='str')

In [28]:
df.shape

(7535, 57)

In [29]:
df.info

<bound method DataFrame.info of            id  Product_Type  Shot  Velocity_1  Velocity_2  Velocity_3  \
0           1             1     1       0.144       0.170       0.188
1        1002             1     2       0.144       0.170       0.182
2        2003             1     3       0.144       0.170       0.182
3        3004             1     4       0.144       0.170       0.182
4        4005             1     5       0.144       0.172       0.176
...       ...           ...   ...         ...         ...         ...
7530  7530659             2   659       0.150       0.166       0.210
7531  7531660             2   660       0.144       0.174       0.206
7532  7532660             2   660       0.144       0.174       0.206
7533  7533661             2   661       0.147       0.174       0.204
7534  7534661             2   661       0.147       0.174       0.204

      High_Velocity  Cylinder_Pressure  Rapid_Rise_Time  Biscuit_Thickness   \
0             2.134                214            0.008                  10
1             2.124                217            0.008                  11
2             2.116                214            0.008                  11
3             2.137                217            0.008                  11
4             2.111                217            0.008                  12
...             ...                ...              ...                 ...
7530          2.492                265            0.011                  17
7531          2.514                264            0.011                  16
7532          2.514                264            0.011                  16
7533          2.532                265            0.012                  18
7534          2.532                265            0.012                  18

      ...  Blow_Hole_2  Stain_2  Dent_2  Deformation_2  Contamination_2  \
0     ...            0        0       0              0                0
1     ...            0        0       0              0                0
2     ...            0        0       0              0                0
3     ...            0        0       0              0                0
4     ...            0        0       0              0                0
...   ...          ...      ...     ...            ...              ...
7530  ...            0        0       0              0                0
7531  ...            0        0       0              0                0
7532  ...            0        0       0              0                0
7533  ...            0        0       0              0                0
7534  ...            0        0       0              0                0

      Impurity_2  Crack_2  Scratch_2  Buring_Mark_2  Inclusions_2
0              0        0          0              0             0
1              0        0          0              0             0
2              0        0          0              0             0
3              0        0          0              0             0
4              0        0          0              0             0
...          ...      ...        ...            ...           ...
7530           0        0          0              0             0
7531           0        0          0              0             0
7532           0        0          0              0             0
7533           0        0          0              0             0
7534           0        0          0              0             0

[7535 rows x 57 columns]>

In [30]:
df.isna().sum()

id                       0
Product_Type             0
Shot                     0
Velocity_1               0
Velocity_2               0
Velocity_3               0
High_Velocity            0
Cylinder_Pressure        0
Rapid_Rise_Time          0
Biscuit_Thickness        0
Clamping_Force           0
Cycle_Time               0
 Pressure_Rise_Time      0
Casting_Pressure         0
Spray_Time               0
Spray_1_Time             0
Spray_2_Time             0
Melting_Furnace_Temp     0
Air_Pressure             0
Air_Pressure_Min         0
Air_Pressure_Max         0
Coolant_Temp             0
Coolant_Temp_Min         0
Coolant_Temp_Max         0
Coolant_Pressure         0
Factory_Temp            90
Factory_Temp_Min        90
Factory_Temp_Max        90
Factory_Humidity        90
Factory_Humidity_Min    90
Factory_Humidity_Max    90
Short_Shot_1             0
Bubble_1                 0
Exfoliation_1            0
Blow_Hole_1              0
Stain_1                  0
Dent_1                   0
Deformation_1            0
Contamination_1          0
Impurity_1               0
Crack_1                  0
Scratch_1                0
Buring_Mark_1            0
Inclusions_1             0
Short_Shot_2             0
Bubble_2                 0
Exfoliation_2            0
Blow_Hole_2              0
Stain_2                  0
Dent_2                   0
Deformation_2            0
Contamination_2          0
Impurity_2               0
Crack_2                  0
Scratch_2                0
Buring_Mark_2            0
Inclusions_2             0
dtype: int64

In [ ]:
# 변수 'Biscuit_Thickness ', 'Clamping_Force ', ' Pressure_Rise_Time' 앞 뒤 공백 제거
df.columns = pd.MultiIndex.from_tuples(
    [(col[0].strip(), col[1].strip()) for col in df.columns]
)

print(df.columns.tolist())

In [ ]:
# factory_cols 결측치 중앙값 처리
factory_cols = [
    'Factory_Temp',
    'Factory_Temp_Min',
    'Factory_Temp_Max',
    'Factory_Humidity',
    'Factory_Humidity_Min',
    'Factory_Humidity_Max'
]

for col in factory_cols:
    df[('Sensor', col)] = df[('Sensor', col)].fillna(
        df[('Sensor', col)].median()
    )

df.isnull().sum().sum()
print("중앙값으로 처리 완료!")

[더미]
id_cols = ["id", "Shot"]

defect_cols = [
    "Short_Shot_1", "Bubble_1", "Exfoliation_1", "Blow_Hole_1", "Stain_1",
    "Dent_1", "Deformation_1", "Contamination_1", "Impurity_1", "Crack_1",
    "Scratch_1", "Buring_Mark_1", "Inclusions_1", "Short_Shot_2", "Bubble_2",
    "Exfoliation_2", "Blow_Hole_2", "Stain_2", "Dent_2", "Deformation_2",
    "Contamination_2", "Impurity_2", "Crack_2", "Scratch_2", "Buring_Mark_2", "Inclusions_2"
]

df = df.dropna(subset=[
    "Factory_Temp",
    "Factory_Temp_Min",
    "Factory_Temp_Max",
    "Factory_Humidity",
    "Factory_Humidity_Min",
    "Factory_Humidity_Max"
])

In [51]:
# High_Velocity, Rapid_Rise_Time, Pressure_Rise_Time가 모두 0인 행 4개 제거
zero_cols = ["High_Velocity", "Rapid_Rise_Time", " Pressure_Rise_Time"]

df = df[(df["High_Velocity"] != 0) |
        (df["Rapid_Rise_Time"] != 0) |
        (df[" Pressure_Rise_Time"] != 0)]

In [52]:
# Factory_Temp, Factory_Humidity = Min, Max가 단순한 설정값이며 측정값은 Max를 아득히 상회함
print("측정값 개수 : ", len(df["Factory_Temp"]))
print("Factory_Temp < Min 개수:",
      (df["Factory_Temp"] < df["Factory_Temp_Min"]).sum())

print("Factory_Temp > Max 개수:",
      (df["Factory_Temp"] > df["Factory_Temp_Max"]).sum())

print("Factory_Humidity < Min 개수:",
      (df["Factory_Humidity"] < df["Factory_Humidity_Min"]).sum())

print("Factory_Humidity > Max 개수:",
      (df["Factory_Humidity"] > df["Factory_Humidity_Max"]).sum())

factory_cols = [
    "Factory_Temp_Min", "Factory_Temp_Max",
    "Factory_Humidity_Min", "Factory_Humidity_Max"
]

측정값 개수 :  7531
Factory_Temp < Min 개수: 0
Factory_Temp > Max 개수: 7441
Factory_Humidity < Min 개수: 0
Factory_Humidity > Max 개수: 7441

In [53]:
# Air_Pressure, Coolant  = Min, Max가 단순한 설정값이며 측정값은 Min, Max 범위 내를 벗어나지 않음
print("측정값 개수 : ", len(df["Air_Pressure"]))
print("Air_Pressure < Min 개수:",
      (df["Air_Pressure"] < df["Air_Pressure_Min"]).sum())

print("Air_Pressure > Max 개수:",
      (df["Air_Pressure"] > df["Air_Pressure_Max"]).sum())


print("측정값 개수 : ", len(df["Coolant_Temp"]))
print("Coolant_Temp < Min 개수:",
      (df["Coolant_Temp"] < df["Coolant_Temp_Min"]).sum())

print("Coolant_Temp > Max 개수:",
      (df["Coolant_Temp"] > df["Coolant_Temp_Max"]).sum())

min_max_cols = [
    "Air_Pressure_Min", "Air_Pressure_Max",
    "Coolant_Temp_Min", "Coolant_Temp_Max"
]

측정값 개수 :  7531
Air_Pressure < Min 개수: 0
Air_Pressure > Max 개수: 0
측정값 개수 :  7531
Coolant_Temp < Min 개수: 0
Coolant_Temp > Max 개수: 0

In [ ]:
# 중앙값 처리
print("Factory_Temp 결측 행 수:",
      df["Factory_Temp"].isna().sum())

print("Factory_Humidity 결측 행 수:",
      df["Factory_Humidity"].isna().sum())

print("둘 중 하나라도 결측인 행 수:",
      df[["Factory_Temp", "Factory_Humidity"]].isna().any(axis=1).sum())

df = df.dropna(subset=["Factory_Temp", "Factory_Humidity"])

Factory_Temp 결측 행 수: 90
Factory_Humidity 결측 행 수: 90
둘 중 하나라도 결측인 행 수: 90

In [55]:
drop_cols = factory_cols + min_max_cols

df_clean = df.drop(columns=drop_cols)

print("=== Drop 후 데이터 ===")
print("행 개수:", df_clean.shape[0])
print("컬럼 개수:", df_clean.shape[1])

=== Drop 후 데이터 ===
행 개수: 7441
컬럼 개수: 49

In [56]:
df2 = df_clean.copy()
print(df2.columns)

Index(['id', 'Product_Type', 'Shot', 'Velocity_1', 'Velocity_2', 'Velocity_3',
       'High_Velocity', 'Cylinder_Pressure', 'Rapid_Rise_Time',
       'Biscuit_Thickness ', 'Clamping_Force ', 'Cycle_Time',
       ' Pressure_Rise_Time', 'Casting_Pressure', 'Spray_Time', 'Spray_1_Time',
       'Spray_2_Time', 'Melting_Furnace_Temp', 'Air_Pressure', 'Coolant_Temp',
       'Coolant_Pressure', 'Factory_Temp', 'Factory_Humidity', 'Short_Shot_1',
       'Bubble_1', 'Exfoliation_1', 'Blow_Hole_1', 'Stain_1', 'Dent_1',
       'Deformation_1', 'Contamination_1', 'Impurity_1', 'Crack_1',
       'Scratch_1', 'Buring_Mark_1', 'Inclusions_1', 'Short_Shot_2',
       'Bubble_2', 'Exfoliation_2', 'Blow_Hole_2', 'Stain_2', 'Dent_2',
       'Deformation_2', 'Contamination_2', 'Impurity_2', 'Crack_2',
       'Scratch_2', 'Buring_Mark_2', 'Inclusions_2'],
      dtype='str')

In [57]:
df2.isna().sum()

id                      0
Product_Type            0
Shot                    0
Velocity_1              0
Velocity_2              0
Velocity_3              0
High_Velocity           0
Cylinder_Pressure       0
Rapid_Rise_Time         0
Biscuit_Thickness       0
Clamping_Force          0
Cycle_Time              0
 Pressure_Rise_Time     0
Casting_Pressure        0
Spray_Time              0
Spray_1_Time            0
Spray_2_Time            0
Melting_Furnace_Temp    0
Air_Pressure            0
Coolant_Temp            0
Coolant_Pressure        0
Factory_Temp            0
Factory_Humidity        0
Short_Shot_1            0
Bubble_1                0
Exfoliation_1           0
Blow_Hole_1             0
Stain_1                 0
Dent_1                  0
Deformation_1           0
Contamination_1         0
Impurity_1              0
Crack_1                 0
Scratch_1               0
Buring_Mark_1           0
Inclusions_1            0
Short_Shot_2            0
Bubble_2                0
Exfoliation_2           0
Blow_Hole_2             0
Stain_2                 0
Dent_2                  0
Deformation_2           0
Contamination_2         0
Impurity_2              0
Crack_2                 0
Scratch_2               0
Buring_Mark_2           0
Inclusions_2            0
dtype: int64

[기존 행]

7535 - 4 - 90 = 7441

=========

[기존 컬럼]

57 - 8 = 49

In [22]:
df2.describe()

,Product_Type,Velocity_1,Velocity_2,Velocity_3,High_Velocity,Cylinder_Pressure,Rapid_Rise_Time,Biscuit_Thickness,Clamping_Force,Cycle_Time,Pressure_Rise_Time,Casting_Pressure,Spray_Time,Spray_1_Time,Spray_2_Time,Melting_Furnace_Temp,Air_Pressure,Coolant_Temp,Coolant_Pressure
count,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000,7535.000000
mean,1.441672,0.148219,0.168801,0.191193,2.319210,239.655607,0.009596,14.309622,306.433311,27.735979,0.039348,856.944127,9.815979,1.409104,1.396045,680.652661,6.109595,26.830126,2.701155
std,0.496619,0.007134,0.004720,0.011563,0.222041,23.305451,0.002148,3.286284,57.274965,8.716156,0.003945,234.815490,1.842438,0.557060,0.716170,25.288666,0.647906,0.525149,0.052408
min,1.000000,0.134000,0.158000,0.172000,0.000000,107.000000,0.000000,0.000000,238.000000,20.200000,0.000000,516.000000,7.000000,0.700000,0.700000,635.300000,4.600000,25.900000,2.580000
25%,1.000000,0.142000,0.166000,0.181000,2.134000,217.000000,0.008000,11.000000,255.000000,20.900000,0.036000,596.000000,8.000000,0.800000,0.800000,656.700000,5.700000,26.500000,2.640000
50%,1.000000,0.144000,0.168000,0.188000,2.161000,239.000000,0.009000,13.000000,258.000000,22.600000,0.041000,1037.000000,9.700000,1.200000,0.800000,680.300000,6.200000,26.800000,2.720000
75%,2.000000,0.156000,0.170000,0.202000,2.523000,265.000000,0.012000,17.000000,372.000000,35.900000,0.043000,1053.000000,12.100000,2.000000,2.000000,703.100000,6.600000,27.200000,2.740000
max,2.000000,0.180000,0.212000,0.234000,2.744000,266.000000,0.021000,24.000000,388.000000,218.600000,0.046000,1164.000000,13.100000,2.500000,3.000000,730.000000,7.100000,28.100000,2.790000